# Generated by Django 4.0.4 on 2022-05-04 17:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('client_fname', models.CharField(help_text='First Name', max_length=200)),
                ('client_lname', models.CharField(help_text='Last Name', max_length=200)),
                ('client_email', models.EmailField(help_text='Email', max_length=254)),
                ('client_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Contact Phone Number', max_length=128, region=None)),
                ('appointment_date', models.DateTimeField()),
                ('appointment_notes', models.TextField(help_text='Appointment Notes (Optional)')),
            ],
        ),
    ]
